"""Initial migration222

Revision ID: 548e7d36c405
Revises: d877d9ea54ad
Create Date: 2018-03-02 18:52:58.724858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548e7d36c405'
down_revision = 'd877d9ea54ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('username2', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'username2')
    # ### end Alembic commands ###
