"""Initial migration11

Revision ID: d877d9ea54ad
Revises: e463a9d6d15a
Create Date: 2018-03-02 18:40:39.350461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd877d9ea54ad'
down_revision = 'e463a9d6d15a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('username', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'username')
    # ### end Alembic commands ###
